website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_user, login_required, logout_user, current_user
from werkzeug.security import generate_password_hash, check_password_hash
from .models import User
from . import db
from . import cipher_suite



auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(request.referrer or url_for('views.home'))
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Senha incorreta.', category='error')
        else:
            flash('Email não existe.', category='error')

    return render_template("login.html", user=current_user)

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(request.referrer or url_for('views.home'))

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    if current_user.is_authenticated:
        return redirect(request.referrer or url_for('views.home'))
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user_Email = User.query.filter_by(email=email).first()
        user_Username = User.query.filter_by(username=username).first()
        if user_Username:
            flash('Nome de usuário já registrado.', category='error')
        elif user_Email:
            flash('Email já registrado.', category='error')
        elif len(password1) < 8 or len(password1) > 128:
            flash('A senha deve conter entre 8 e 128 caracteres.', category='error')
        elif password1 != password2:
            flash('Senhas não coincidem.', category='error')
        else:
            new_user = User(username=username, email=email, password=generate_password_hash(password1, method='scrypt'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))

    return render_template("signup.html", user=current_user)

@auth.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        password0 = request.form.get('password0')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')
        matricula = request.form.get('matricula')

        user = User.query.get(current_user.id)

        # Update Username
        if username and username != user.username:
            user_Username = User.query.filter_by(username=username).first()
            if user_Username:
                flash('Nome de usuário já registrado.', category='error')
            else:
                user.username = username
                flash('Nome de usuário alterado com sucesso.', category='success')

        # Update Email
        if email and email != user.email:
            user_Email = User.query.filter_by(email=email).first()
            if user_Email:
                flash('Email já registrado.', category='error')
            else:
                user.email = email
                flash('Email alterado com sucesso.', category='success')

        # Update Password
        if password0 and password1 and password2:
            if not check_password_hash(user.password, password0):
                flash('Senha incorreta.', category='error')
            elif password0 == password1:
                flash('A senha antiga e a nova senha não podem ser iguais.', category='error')    
            elif password1 != password2:
                flash('Senhas novas não coincidem.', category='error')
            elif len(password1) < 8 or len(password1) > 128:
                flash('A senha deve conter entre 8 e 128 caracteres.', category='error')
            else:
                user.password = generate_password_hash(password1, method='scrypt')
                flash('Senha alterada com sucesso.', category='success')

        # Update matricula
        if matricula and matricula != user.matricula:
            encrypted_matricula = cipher_suite.encrypt(matricula.encode()).decode()
            user.matricula = encrypted_matricula
            flash('Matrícula alterada com sucesso.', category='success')
        
        db.session.commit()

    return render_template("profile.html", user=current_user)

website/templates/adduser.html
{% extends "form.html" %}
{% block form_title %}Perfil{% endblock %}
{% block form_action %}{{ url_for('auth.profile') }}{% endblock %}
{% block form_input %}
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="icon-edit" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round"
    stroke-linejoin="round" stroke-width="2">
    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
  </symbol>
</svg>

<div class="form-floating">
  <input type="username" name="username" class="form-control rounded-bottom-0" id="username" placeholder="Username"
    value="{{ user.username }}" disabled>
  <label for="username">Usuário</label>
  <button class="btn rounded-circle border-0 position-absolute top-50 end-0 translate-middle-y edit-btn"
    type="button" data-input="username">
    <svg width="24" height="24">
      <use xlink:href="#icon-edit"></use>
    </svg>
  </button>
</div>
<div class="form-floating">
  <input type="email" name="email" class="form-control rounded-0" id="email" placeholder="name@example.com"
    value="{{ user.email }}" disabled>
  <label for="email">Email</label>
  <button class="btn rounded-circle border-0 position-absolute top-50 end-0 translate-middle-y edit-btn"
    type="button" data-input="email">
    <svg width="24" height="24">
      <use xlink:href="#icon-edit"></use>
    </svg>
  </button>
</div>
<div class="form-floating mb-3">
  <input type="password" name="matricula" class="form-control rounded-top-0" id="matricula" placeholder="Password" {%
    if user.matricula %}value="********" disabled{% endif %}>
  <label for="matricula">Número de Matrícula</label>
  <button class="btn rounded-circle border-0 position-absolute top-50 end-0 translate-middle-y edit-btn"
    type="button" data-input="matricula">
    {% if user.matricula %}
    <svg width="24" height="24">
      <use xlink:href="#icon-edit"></use>
    </svg>
    {% endif %}
  </button>
</div>
<hr class="my-4">
<h4 class="mb-3">Alterar senha</h4>
<div class="form-floating">
  <input type="password" name="password0" class="form-control rounded-bottom-0" id="password0" placeholder="Password">
  <label for="password0">Senha atual</label>
</div>
<div class="form-floating">
  <input type="password" name="password1" class="form-control rounded-0" id="password1" placeholder="Password">
  <label for="password1">Nova senha</label>
</div>
<div class="form-floating mb-3">
  <input type="password" name="password2" class="form-control rounded-top-0" id="password2" placeholder="Password">
  <label for="password2">Confirme a senha</label>
</div>
{% endblock %}
{% block form_submit %}Salvar{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="auto">

<head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
      integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
   <link href="{{ url_for('static', filename='css/main.css') }}" rel="stylesheet" type="text/css">
   <title>{% block title %}Cursos Hospital Madre Teresa{%endblock %}
   </title>
</head>

<body>
   <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
         <path
            d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z" />
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
         <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
         <path
            d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
         <path
            d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
         <path
            d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
      </symbol>
   </svg>
   <div class="dropup position-fixed bottom-0 end-0 mb-5 py-4 me-3 bd-mode-toggle">
      <button class="btn btn-info py-2 dropdown-toggle d-flex align-items-center" id="bd-theme" type="button"
         aria-expanded="false" data-bs-toggle="dropdown" aria-label="Toggle theme (auto)">
         <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
         </svg>
         <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
      </button>
      <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
         <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
               aria-pressed="false">
               <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                  <use href="#sun-fill"></use>
               </svg>
               Light
               <svg class="bi ms-auto d-none" width="1em" height="1em">
                  <use href="#check2"></use>
               </svg>
            </button>
         </li>
         <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
               aria-pressed="false">
               <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                  <use href="#moon-stars-fill"></use>
               </svg>
               Dark
               <svg class="bi ms-auto d-none" width="1em" height="1em">
                  <use href="#check2"></use>
               </svg>
            </button>
         </li>
         <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
               aria-pressed="true">
               <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                  <use href="#circle-half"></use>
               </svg>
               Auto
               <svg class="bi ms-auto d-none" width="1em" height="1em">
                  <use href="#check2"></use>
               </svg>
            </button>
         </li>
      </ul>
   </div>
   <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="facebook" viewBox="0 0 16 16">
         <path
            d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z" />
      </symbol>
      <symbol id="instagram" viewBox="0 0 16 16">
         <path
            d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z" />
      </symbol>
      <symbol id="twitter" viewBox="0 0 16 16">
         <path
            d="M5.026 15c6.038 0 9.341-5.003 9.341-9.334 0-.14 0-.282-.006-.422A6.685 6.685 0 0 0 16 3.542a6.658 6.658 0 0 1-1.889.518 3.301 3.301 0 0 0 1.447-1.817 6.533 6.533 0 0 1-2.087.793A3.286 3.286 0 0 0 7.875 6.03a9.325 9.325 0 0 1-6.767-3.429 3.289 3.289 0 0 0 1.018 4.382A3.323 3.323 0 0 1 .64 6.575v.045a3.288 3.288 0 0 0 2.632 3.218 3.203 3.203 0 0 1-.865.115 3.23 3.23 0 0 1-.614-.057 3.283 3.283 0 0 0 3.067 2.277A6.588 6.588 0 0 1 .78 13.58a6.32 6.32 0 0 1-.78-.045A9.344 9.344 0 0 0 5.026 15z" />
      </symbol>
      <symbol id="icon-search" viewBox="0 0 16 16">
         <path
            d="M5.75 9.8A4.045 4.045 0 011.7 5.75 4.045 4.045 0 015.75 1.7 4.045 4.045 0 019.8 5.75 4.045 4.045 0 015.75 9.8zm5.4 0h-.711l-.252-.243A5.824 5.824 0 0011.6 5.75a5.85 5.85 0 10-5.85 5.85 5.824 5.824 0 003.807-1.413l.243.252v.711l4.5 4.491 1.341-1.341z">
         </path>
      </symbol>
      <symbol id="icon-sliders" viewBox="0 0 16 16">
         <path
            d="M11.5 2a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM9.05 3a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0V3h9.05zM4.5 7a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zM2.05 8a2.5 2.5 0 0 1 4.9 0H16v1H6.95a2.5 2.5 0 0 1-4.9 0H0V8h2.05zm9.45 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3zm-2.45 1a2.5 2.5 0 0 1 4.9 0H16v1h-2.05a2.5 2.5 0 0 1-4.9 0H0v-1h9.05z">
         </path>
      </symbol>
   </svg>

   <header class="fixed-bottom bg-info">
      <div class="container d-flex mw-100">
         <nav class="navbar navbar-expand-md col-md-6">
            <div class="container-fluid justify-content-start" title="">
               <a class="navbar-brand d-flex align-items-center" href="/">
                  <img class="border border-2 border-body bg-body rounded-circle"
                     src="https://www.hospitalmadreteresa.org.br/favicon.ico" alt="mdo" width="32" height="32"
                     loading="lazy">
                  <span class="fs-4 fw-bolder px-1 text-light">MT Cursos</span>
               </a>
            </div>
         </nav>
         <nav class="navbar navbar-expand-md col-md-6">
            <div class="container-fluid justify-content-end align-items-center">
               {% if user.is_authenticated %}
               <div class="dropup">
                  <a href="/" class="d-block link-body-emphasis text-decoration-none dropdown-toggle"
                     data-bs-toggle="dropdown" aria-expanded="false">
                     <img class="border border-2 border-body bg-body rounded-circle"
                        src="https://www.hospitalmadreteresa.org.br/favicon.ico" alt="mdo" width="32" height="32"
                        loading="lazy">
                  </a>
                  <ul class="dropdown-menu dropdown-menu-end text-small shadow">
                     <li><a class="dropdown-item" id="profile">Perfil</a></li>
                     <li><a class="dropdown-item" id="logout" href="/logout">Sair</a></li>
                  </ul>
               </div>
               {% else %}
               <div class="d-flex justify-content-end align-items-center gap-2">
                  <a class="link-body-emphasis text-decoration-none text-light me-2"
                     id="login" href="/login"><strong>Login</strong></a>
                  <a class="btn btn-outline-light" id="signup" href="/signup"><strong>Registrar</strong></a>
               </div>
               {% endif %}
            </div>
         </nav>
      </div>
   </header>

   <main>
      {% block main %}
      {% endblock %}
   </main>

   <footer class="pt-4">
      <div class="container d-flex justify-content-between align-items-center py-4 border-top">
         <div class="col-md-6">
            <span class="mb-md-0 text-body-secondary">&copy; Site, 2023</span>
         </div>
         <ul class="col-md-6 justify-content-end list-unstyled d-flex mb-md-0">
            <li class="ms-3">
               <a class="text-body-secondary" href="" title="Twitter" target="_blank" rel="noopener noreferrer">
                  <svg class="bi" width="24" height="24">
                     <use xlink:href="#twitter" />
                  </svg>
               </a>
            </li>
            <li class="ms-3">
               <a class="text-body-secondary" href="" title="Instagram" target="_blank" rel="noopener noreferrer">
                  <svg class="bi" width="24" height="24">
                     <use xlink:href="#instagram" />
                  </svg>
               </a>
            </li>
            <li class="ms-3">
               <a class="text-body-secondary" href="" title="Facebook" target="_blank" rel="noopener noreferrer">
                  <svg class="bi" width="24" height="24">
                     <use xlink:href="#facebook" />
                  </svg>
               </a>
            </li>
         </ul>
      </div>
   </footer>

   <script src="https://cdn.jsdelivr.net/npm/jquery@3.6.4/dist/jquery.min.js"></script>
   <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
      crossorigin="anonymous"></script>
   <script type="text/javascript" data-cfasync="false"
      src="{{ url_for('static', filename='js/color-modes.js') }}"></script>
   <script type="module" src="{{ url_for('static', filename='js/main.js') }}"></script>
</body>

</html>

website/templates/login.html
{% extends "form.html" %}
{% block title %}Log in - Cursos Hospital Madre Teresa{% endblock %}
{% block form_title %}Login{% endblock %}
{% block form_action %}{{ url_for('auth.login') }}{% endblock %}
{% block form_input %}
<div class="form-floating">
  <input type="email" name="email" class="form-control rounded-bottom-0" id="email" placeholder="name@example.com"
    required>
  <label for="email">Email</label>
</div>
<div class="form-floating mb-3">
  <input type="password" name="password" class="form-control rounded-top-0" id="password" placeholder="Password"
    required>
  <label for="password">Senha</label>
</div>
{% endblock %}
{% block form_submit %}Log in{% endblock %}

website/templates/profile.html
{% extends "form.html" %}
{% block form_title %}Perfil{% endblock %}
{% block form_action %}{{ url_for('auth.profile') }}{% endblock %}
{% block form_input %}
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="icon-edit" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-linecap="round"
    stroke-linejoin="round" stroke-width="2">
    <path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7" />
    <path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z" />
  </symbol>
</svg>

<div class="form-floating">
  <input type="username" name="username" class="form-control rounded-bottom-0" id="username" placeholder="Username"
    value="{{ user.username }}" disabled>
  <label for="username">Usuário</label>
  <button class="btn rounded-circle border-0 position-absolute top-50 end-0 translate-middle-y edit-btn"
    type="button" data-input="username">
    <svg width="24" height="24">
      <use xlink:href="#icon-edit"></use>
    </svg>
  </button>
</div>
<div class="form-floating">
  <input type="email" name="email" class="form-control rounded-0" id="email" placeholder="name@example.com"
    value="{{ user.email }}" disabled>
  <label for="email">Email</label>
  <button class="btn rounded-circle border-0 position-absolute top-50 end-0 translate-middle-y edit-btn"
    type="button" data-input="email">
    <svg width="24" height="24">
      <use xlink:href="#icon-edit"></use>
    </svg>
  </button>
</div>
<div class="form-floating mb-3">
  <input type="password" name="matricula" class="form-control rounded-top-0" id="matricula" placeholder="Password" {%
    if user.matricula %}value="********" disabled{% endif %}>
  <label for="matricula">Número de Matrícula</label>
  <button class="btn rounded-circle border-0 position-absolute top-50 end-0 translate-middle-y edit-btn"
    type="button" data-input="matricula">
    {% if user.matricula %}
    <svg width="24" height="24">
      <use xlink:href="#icon-edit"></use>
    </svg>
    {% endif %}
  </button>
</div>
<hr class="my-4">
<h4 class="mb-3">Alterar senha</h4>
<div class="form-floating">
  <input type="password" name="password0" class="form-control rounded-bottom-0" id="password0" placeholder="Password">
  <label for="password0">Senha atual</label>
</div>
<div class="form-floating">
  <input type="password" name="password1" class="form-control rounded-0" id="password1" placeholder="Password">
  <label for="password1">Nova senha</label>
</div>
<div class="form-floating mb-3">
  <input type="password" name="password2" class="form-control rounded-top-0" id="password2" placeholder="Password">
  <label for="password2">Confirme a senha</label>
</div>
{% endblock %}
{% block form_submit %}Salvar{% endblock %}

website/templates/signup.html
{% extends "form.html" %}
{% block title %}Cadastro - Cursos Hospital Madre Teresa{% endblock %}
{% block form_title %}Cadastro{% endblock %}
{% block form_action %}{{ url_for('auth.signup') }}{% endblock %}
{% block form_input %}
<div class="form-floating">
  <input type="username" name="username" class="form-control rounded-bottom-0" id="username" placeholder="Username"
    required>
  <label for="username">Usuário</label>
</div>
<div class="form-floating">
  <input type="email" name="email" class="form-control rounded-0" id="email" placeholder="name@example.com"
    required>
  <label for="email">Email</label>
</div>
<div class="form-floating">
  <input type="password" name="password1" class="form-control rounded-0" id="password1" placeholder="Password"
    required>
  <label for="password1">Senha</label>
</div>
<div class="form-floating mb-3">
  <input type="password" name="password2" class="form-control rounded-top-0" id="password2" placeholder="Password"
    required>
  <label for="password2">Confirme a senha</label>
</div>
{% endblock %}
{% block form_submit %}Cadastrar{% endblock %}
{% block form_extra %}
<small class="text-body-secondary">Ao clicar em cadastrar, você concorda com os termos de uso.</small>
{% endblock %}